version: '3.8'

services:
  video-channel-backend:
    build: .
    ports:
      - "4000:4000"
    depends_on:
      - db
    environment:
      - APP_PORT=4000
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=admin
      - DB_PASSWORD=Pass123
      - DB_NAME=video_db
      - JWT_SECRET=secret
    networks:
      - video

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Pass123
      POSTGRES_DB: video_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - video

networks:
  video:
    name: video
    external: true

volumes:
  postgres_data: